export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ORDER_PRODUCTS_BY_CATEGORY = "ORDER_PRODUCTS_BY_CATEGORY";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const ORDER_PRODUCTS_BY_NAME='ORDER_PRODUCTS_BY_NAME'
export const ADD_REMOVE_FROM_CART='ADD_REMOVE_FROM_CART'

